POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Fastify Event",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/18d175d0-fbc7-45bf-b7a6-3560e8a0c901/attendees
Content-Type: application/json

{
  "name": "Andrew G",
  "email": "email18@email.com"
}

###

GET http://localhost:3333/events/c2935e4f-e3c2-477b-8ea9-6647d59582e0
Content-Type: application/json

###

GET http://localhost:3333/attendees/1/badge
Content-Type: application/json

###

GET http://localhost:3333/attendees/5/check-in
Content-Type: application/json

###

GET http://localhost:3333/events/18d175d0-fbc7-45bf-b7a6-3560e8a0c901/attendees?query=Andrew
Content-Type: application/json
