POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "New Unite Summit",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/aee468f7-cae3-4a78-8d76-6737966bba26/attendees
Content-Type: application/json

{
  "name": "Andrew G",
  "email": "email@email.com"
}
