version: '3.8'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-eventsfy
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventsfypostgres
      POSTGRES_PASSWORD: evfyadmin
      POSTGRES_DB: eventsfy
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - eventsfynetwork
    
  events-fy:
    build:
      context: .
    container_name: eventsfy-pg
    ports:
      - 3000:3333
    environment:
      - DATABASE_URL=postgresql://eventsfypostgres:evfyadmin@postgres:5432/eventsfy
    depends_on:
      - postgres
    networks:
      - eventsfynetwork

networks:
  eventsfynetwork:
    driver: bridge

volumes:
  db: