version: '3.8'

services:

  postgres:
    build:
      context: .
    container_name: eventsfy-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventsfypostgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: eventsfy
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
